### ISSUE TITLE
invalid id namespace

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [nostalgy/nostalgy#18]
official script fails to extract extension id

```
# http://kb.mozillazine.org/Determine_extension_ID
# Retrieve the extension id for an addon from its install.rdf
get_extension_id() {
    unzip -q -c $1 install.rdf | xmlstarlet sel \
    -N RDF=http://www.w3.org/1999/02/22-rdf-syntax-ns# \
    -N em=http://www.mozilla.org/2004/em-rdf# \
    -t -v \
    "//RDF:Description[@about='urn:mozilla:install-manifest']/em:id"
}
```

**Comment by caugner** [comment]
Closing this issue, as it is out of scope.

The "official" script (from 2010) extracts a property from an RDF file (`install.rdf`) that is not present in this add-on. Furthermore, since the Thunderbird add-ons platform accepts this add-on without this file, it is obviously not required. Therefore the script cannot be expected to work with the Nostalgy XPI.
