### ISSUE TITLE
Navigation highlighting gone

### ISSUE THREAD

**Issue by clecap** [nostalgy/nostalgy#66]
A while ago nostalgy had a wonderful feature which now seems to be gone. I cannot say whether it vanished by an update or is a consequence of my moving from Windows to Mac.

When you enter a search string a list of folders appears. You can navigate in the list of folders with the cursor keys and the currently selected entry in the list was highlighted. Now this highlighting is gone.

Anything which can be done to get it back?

**Comment by Markmull** [comment]
I can't see if there is any discussion board in GitHub. I created an account recently because of a Nostalgy functionality degrade described as follows: I updated Thunderbird somewhat recently to 68.8.0 & now Nostalgy is not as keyboard friendly. For example, the online usage directions state "Before you type anything in the folder completion box, the popup displays the most recently selected folders. You can choose one of them with the UP/DOWN keys." Nostalgy did used work that way, but now, after typing "s" for moving the email to a location, the recent locations still pop up, but it does not highlight one or allow me to use the up arrow to highlight one & hit Enter to move it. I must first begin typing part of the location I want, only then can I use the up arrow to highlight the location to move it there. There are some other functionality losses similar to that. I may look at backing out of recent TBird updates (though I don't know how far back I have to go). Nostalgy is basically a killer-addon for me. It's become essential.

**Comment by MLopez-Ibanez** [comment]
> Anything which can be done to get it back?

This works for me in Linux with this version: https://github.com/MLopez-Ibanez/nostalgy

Maybe it is a macos issue.

**Comment by MLopez-Ibanez** [comment]
> I may look at backing out of recent TBird updates (though I don't know how far back I have to go). Nostalgy is basically a killer-addon for me. It's become essential.

@Markmull Unfortunately, it is not feasible to keep old versions of TB around as they have security bugs. 

All the degradation in functionality that you have observed is due to TB changing interfaces and developers working around those changes without a clear idea of what they are doing.

However, this will not work for TB 78 in June 2020, because Nostalgy will need to be a WebExtension by them otherwise NOTHING will work. There is no way to hack around or disable non-working functionality to make some parts of it work. It will not be possible to install it.  See https://developer.thunderbird.net/add-ons/tb78
 
How can you help? Read the docs: https://thunderbird-webextensions.readthedocs.io and make a list of interfaces that are needed for Nostalgy. If Nostalgy needs to do something and it is not there, then it  needs to be requested from Mozilla.

**Comment by jdbeutel** [comment]
Will it need to be a WebExtension or MailExtension?  I don't know what 
those are, but the page you linked recommends MailExtension over 
WebExtension, so I wonder which one I should look into.

Cheers,
11011011

**Comment by caugner** [comment]
I strongly believe that this is a duplicate of #55, i.e. a folder from the "recent folder" suggestions cannot be selected, while a folder from the search results can be selected.
